Should add functions for "Get Invite" and "Delete Invite" routes, fix minor issue in getChannelMessages.
princesslana/smalldkt pull request #19
Opened 2019-06-15 15:28 UTC by RedTechKnight

This will add the extensions functions 'getInvite' and 'deleteInvite' to the SmallDData<T> type, which correspond to the routes https://discordapp.com/developers/docs/resources/invite#get-invite and https://discordapp.com/developers/docs/resources/invite#delete-invite respectively. 

It also adds a data class to be used for storing the response for those paths. This class also makes use of a throwaway definition of a Guild object to make parsing the response easier, it should be able to be replaced easily with a more complete definition later if needed.

2019-06-16 00:50 UTC, CoreyShupe requested changes

2019-06-16 00:50 UTC, CoreyShupe commented on src/main/kotlin/com/github/princesslana/smalldkt/type/invite/Requests.kt
> +  "/invites/$code?" + queryString{
The `queryString` adds the `?` for you, no need to have it here

2019-06-16 00:50 UTC, CoreyShupe commented on src/main/kotlin/com/github/princesslana/smalldkt/type/invite/resources/InviteEntity.kt
> +data class GuildObjectStub(
Is there any way to name this better, maybe something like `InvitePartialGuild` or something to that nature. Due to it being a top level class I'd rather not clutter the namespace with something vague like this.

2019-06-16 00:50 UTC, CoreyShupe commented on src/main/kotlin/com/github/princesslana/smalldkt/type/invite/resources/InviteEntity.kt
> +data class InviteData(
Look at other conventions to see how I kind of want the resources to be made:
https://github.com/princesslana/smalldkt/blob/master/src/main/kotlin/com/github/princesslana/smalldkt/type/channel/resources/ChannelEntity.kt#L11-L52
This kind of thing is used to allow for segmenting pieces and helping events, once everything is written out if it's used once then it'll be collapsed. Also, the name for this is kind of odd, see the connection with docs and naming conventions in the Channel as it should be similar.

2019-06-16 00:50 UTC, CoreyShupe commented on src/main/kotlin/com/github/princesslana/smalldkt/type/invite/resources/InviteEntity.kt
> +        val guild: GuildObjectStub,
This is meant to be optional according to the docs.

2019-06-16 00:50 UTC, CoreyShupe commented on src/main/kotlin/com/github/princesslana/smalldkt/type/invite/resources/InviteEntity.kt
> +data class InviteData(
Where is this kind of data class coming from in the documentation? It seems like a mix of a few or from field testing. Please use the official docs to write the data classes then we can move from there. For reference this object should probably be a mix with the object and metadata with the meta-data parts being all optional.

2019-06-16 00:50 UTC, CoreyShupe commented on src/main/kotlin/com/github/princesslana/smalldkt/type/invite/resources/InviteEntity.kt
> +data class GuildObjectStub(
I also think we should just link this as a regular guild until one of the fields doesn't exist then work from there. Doing field testing with this kind of makes it vague as the docs don't necessarily define partial ~~afaik~~. They don't define partial, I'm going to be adding in special classes and you can start where every field is optional. Like a PartialGuild will have all the fields of a Guild but all of them will be optional. That's the best definition I got from people about what partial is.

2019-06-16 12:28 UTC, RedTechKnight commented on src/main/kotlin/com/github/princesslana/smalldkt/type/invite/Requests.kt
> +  "/invites/$code?" + queryString{
Ah, terribly sorry. Fixed it in one of my new commits.

2019-06-16 12:30 UTC, RedTechKnight commented on src/main/kotlin/com/github/princesslana/smalldkt/type/invite/resources/InviteEntity.kt
> +data class GuildObjectStub(
Moved it to its own file under "type/guild/resources/GuildEntity.kt" and renamed it to PartialGuild, hopefully fixes this issue.

2019-06-16 12:32 UTC, RedTechKnight commented on src/main/kotlin/com/github/princesslana/smalldkt/type/invite/resources/InviteEntity.kt
> +data class InviteData(
The class name has been changed to follow the project's naming conventions.

2019-06-16 12:35 UTC, RedTechKnight commented on src/main/kotlin/com/github/princesslana/smalldkt/type/invite/resources/InviteEntity.kt
> +        val guild: GuildObjectStub,
Among the other changes, the guild field is now defined as optional in the type as well.

2019-06-16 12:43 UTC, RedTechKnight commented on src/main/kotlin/com/github/princesslana/smalldkt/type/invite/resources/InviteEntity.kt
> +data class InviteData(
This is now the "InviteImpl" class more or less, which consists of the elements from the Invite object defined in the docs with the elements from the InviteMetadata object, all of which are optional in the new definition.

2019-06-16 12:46 UTC, RedTechKnight commented on src/main/kotlin/com/github/princesslana/smalldkt/type/invite/resources/InviteEntity.kt
> +data class GuildObjectStub(
The class has now been redefined as a PartialGuild, although not all fields are marked as Optional.

2019-06-21 17:11 UTC, CoreyShupe requested changes

2019-06-21 17:11 UTC, CoreyShupe commented on src/main/kotlin/com/github/princesslana/smalldkt/type/guild/resources/GuildEntity.kt
> +    val afk_channel_id: Optional<Snowflake>?
this should have a default value of Optional.absent()
all optional marked items in docs need default values, this goes for everything else in this PR

2019-06-21 17:31 UTC, CoreyShupe approved these changes

2019-06-21 17:31 UTC, CoreyShupe commented
I was being dumb, my bad

2019-06-21 17:31 UTC, merged